[project]
authors = ["ff4f00 <mail@ff4f00.io>"]
channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
name = "IO"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
jupyterlab = ">=4.3.6,<5"
conda = ">=25.3.0,<26"
max = ">=25.3.0.dev2025033022,<26"
