#!/bin/zsh

sudo rm -rf /usr/local/bin/*
sudo rm -rf /usr/local/lib/*
sudo rm -rf /usr/local/doc/*
sudo rm -rf /usr/local/include/*
sudo rm -rf /usr/local/share/*
rm -rf /tmp/*

source "$HOME/.•/.src/cmake"
source "$HOME/.•/.src/ninja"

for src in msgpack \
           lpeg \
           luajit \
           libuv \
           luv \
           libvterm \
           gettext \
           tree-sitter \
           unibilium; do
  source "$HOME/.•/.src/$src"
done

sudo rm -rf /tmp/*

ver="0.10.4"
url="https://github.com/neovim/neovim/archive/refs/tags/v$ver.tar.gz"
src="neovim-$ver"


dir="/tmp"
zip="tar.gz"

# DOWNLOAD
curl -o "$dir/$src.$zip" -OL "$url"

# UNPACK
tar -xzvf "$dir/$src.$zip" -C $dir

for color in blue darkblue delek desert elflord evening habamax industry koehler lunaperche morning murphy pablo peachpuff quiet retrobox ron shine slate sorbet torte wildcharm zaibatsu zellner; do
  rm -f "$dir/$src/runtime/colors/$color.vim"
done

# am:pm
touch "$dir/$src/runtime/colors/am.vim" "$dir/$src/runtime/colors/pm.vim"

# INSTALL
cd "$dir/$src" && make CMAKE_BUILD_TYPE=Release && sudo make install



if ! command -v neovide &> /dev/null; then
  brew install neovide --cask
fi


mkdir -p $HOME/.config/neovide
cat <<EOL > $HOME/.config/neovide/config.toml
title-hidden = true
frame = 'buttonless'

dynamic_padding = true

fork = false
idle = true
maximized = false
neovim-bin = "/usr/local/bin/nvim"
no-multigrid = false
srgb = false
tabs = true
theme = "auto"
vsync = true
wsl = false

[font]
normal = ["MonoLisa Nerd Font"]
size = 14
EOL



git clone https://github.com/NvChad/starter ~/.config/nvim && nvim
